### ISSUE TITLE
Crash with lithium

### ISSUE THREAD

**Issue by machinesmith42** [Virtuoel/Towelette#31]
MultiMC version: 0.6.11-1430

Minecraft folder is:
D:/Downloads/mmc-stable-win32(2)/MultiMC/instances/1.16.12/.minecraft

Java path is:
C:/Program Files/ojdkbuild/java-14-openjdk-jre-14.0.1-1/bin/javaw.exe

Java is version 14.0.1, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  D:/Downloads/mmc-stable-win32(2)/MultiMC/instances/1.16.12/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/datafixerupper/3.0.25/datafixerupper-3.0.25.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/intermediary/1.16.1/intermediary-1.16.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.2.64/tiny-remapper-0.2.2.64.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/ow2/asm/asm/8.0/asm-8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/ow2/asm/asm-analysis/8.0/asm-analysis-8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/ow2/asm/asm-commons/8.0/asm-commons-8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/ow2/asm/asm-tree/8.0/asm-tree-8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/ow2/asm/asm-util/8.0/asm-util-8.0.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/fabric-loader/0.8.9+build.203/fabric-loader-0.8.9+build.203.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/minecraft/1.16.1/minecraft-1.16.1-client.jar

Native libraries:
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [❌] appleskin-mc1.16-fabric-1.0.11.jar (disabled)
  [❌] carpet-extra-1.16-1.4.0.jar (disabled)
  [❌] chat-up-1.0.0-1.16.jar (disabled)
  [❌] cleardespawn-1.16-fabric0.13.1-1.1.0.jar (disabled)
  [❌] conflictinharmony-1.0.1+1.16.jar (disabled)
  [❌] connected-block-textures-0.1.1+1.16.jar (disabled)
  [❌] CraftPresence-Fabric-1.16.1-1.6.6.jar (disabled)
  [❌] dark-loading-screen-1.3.2.jar (disabled)
  [❌] data-loader-2.1.0+mc1.16.1.jar (disabled)
  [❌] durabilityviewer-1.16-fabric0.13.1-1.7.1(1).jar (disabled)
  [✔️] fabric-api-0.14.0+build.371-1.16
  [❌] fabric-carpet-1.16-1.4.0+v200623.jar (disabled)
  [❌] g4mespeed-1.0.6-mc1.16.1-release(1).jar (disabled)
  [❌] Hwyla-fabric-1.16-1.9.22-74.jar (disabled)
  [❌] immersive-portals-0.24-mc1.16.1-fabric.jar (disabled)
  [❌] itemscroller-fabric-1.16.0-0.15.0-dev.20200624.214738.jar (disabled)
  [❌] lambdacontrols-fabric-1.4.1+1.16.1.jar (disabled)
  [❌] lambdynamiclights-fabric-1.2.2+1.16.1.jar (disabled)
  [❌] light-overlay-5.4.0.jar (disabled)
  [✔️] lithium-fabric-mc1.16.1-0.5.1
  [❌] logical_zoom-0.0.2.jar (disabled)
  [❌] malilib-fabric-1.16.0-0.10.0-dev.21+beta.2.jar (disabled)
  [❌] minihud-fabric-1.16.0-0.19.0-dev.20200625.014835.jar (disabled)
  [❌] modmenu-1.12.2+build.17.jar (disabled)
  [❌] mousewheelie-1.4.16+mc1.16-rc1.jar (disabled)
  [❌] okzoomer-4.0.0-alpha.3.1.16.pre5.jar (disabled)
  [❌] phosphor-fabric-mc1.16.1-0.6.0+build.7.jar (disabled)
  [❌] prone-0.1.0.jar (disabled)
  [❌] quickshulker-1.1.5-1.16.jar (disabled)
  [❌] RoughlyEnoughItems-4.5.5.jar (disabled)
  [❌] roughly-searchable-2.0.0+1.16.1.jar (disabled)
  [❌] shulkerboxtooltip-2.1.0+1.16.1.jar (disabled)
  [❌] sodium-fabric-mc1.16.1-0.1.0.6-ipcompat.jar (disabled)
  [❌] sodium-fabric-mc1.16.1-0.1.0.jar (disabled)
  [❌] stackablepotionsandbuckets-1.0.jar (disabled)
  [❌] tiny-mod-0.0.2.jar (disabled)
  [✔️] Towelette-4.1.1+1.16.1
  [❌] trinkets-2.6.3(1).jar (disabled)
  [❌] tweakeroo-fabric-1.16.1-0.10.0-dev.20200712.005446.jar (disabled)
  [❌] Xaeros_Minimap_20.18.0.1_Fabric_1.16.1.jar (disabled)
  [❌] XaerosWorldMap_1.7.4_Fabric_1.16.1.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir D:/Downloads/mmc-stable-win32(2)/MultiMC/instances/1.16.12/.minecraft --assetsDir D:/Downloads/mmc-stable-win32(2)/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:+UnlockExperimentalVMOptions, -XX:+UseZGC, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms409m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 13300

Using onesix launcher.

[19:51:09] [main/INFO]: Loading for game Minecraft 1.16.1
[19:51:10] [main/INFO]: [FabricLoader] Loading 43 mods: fabric-screen-handler-api-v1@1.0.1+f362c86e02, minecraft@1.16.1, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, fabric-renderer-api-v1@0.2.13+eae12eb802, fabric-keybindings-v0@0.2.0+3fa9f7c502, fabric-command-api-v1@1.0.8+5ce5339802, towelette@4.1.1+1.16.1, fabricloader@0.8.9+build.203, fabric-tool-attribute-api-v1@1.1.4+5794386e02, fabric-renderer-indigo@0.3.2+4d66bed502, lithium@0.5.1, fabric-containers-v0@0.1.8+045df74f02, fabric-object-builder-api-v1@1.5.5+e00ecb5f02, fabric-dimensions-v1@1.0.0+a71b305302, fabric-biomes-v1@0.2.7+059ea86602, fabric-crash-report-info-v1@0.1.2+b7f9825d02, fabric-events-interaction-v0@0.3.3+7066030f02, fabric-item-api-v1@1.0.0+16acbe5b02, statement@3.0.4+1.16.1, fabric-api-base@0.1.3+12a8474c02, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, fabric-key-binding-api-v1@1.0.0+e16a977402, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-resource-loader-v0@0.2.5+059ea86602, fabric-textures-v0@1.0.4+eae12eb802, fabric-content-registries-v0@0.1.9+059ea86602, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, fabric-rendering-fluids-v1@0.1.8+b7084faa02, fabric-registry-sync-v0@0.3.8+7dba2d6c02, fabric-commands-v0@0.2.0+52d3083602, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, fabric-lifecycle-events-v1@1.0.0+b0993bc102, fabric-mining-levels-v0@0.1.2+b764ce9902, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, fabric-loot-tables-v1@0.1.10+059ea86602, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, fabric@0.14.0+build.371-1.16, fabric-particles-v1@0.2.1+0a6f2a7002, fabric-item-groups-v0@0.2.0+438f963602, fabric-models-v0@0.1.0+dfdb52d602, fabric-networking-v0@0.1.10+e00ecb5f02, fabric-object-builders-v0@0.6.0+da175ad602
[19:51:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/D:/Downloads/mmc-stable-win32(2)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[19:51:15] [main/INFO]: Loaded configuration file for Lithium: 54 options available, 1 override(s) found
[19:51:15] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
[19:51:16] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by user configuration) disables it and children
[19:51:21] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[19:51:21] [main/INFO]: Setting user: MachineSmith42
---- Minecraft Crash Report ----
// You're mean.

Time: 7/30/20, 7:51 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'towelette'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Tag minecraft:leaves used before it was bound
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Tag minecraft:leaves used before it was bound
	at net.minecraft.class_5120$class_5121.method_26776(class_5120.java:67)
	at net.minecraft.class_5120$class_5121.method_15141(class_5120.java:78)
	at net.minecraft.class_2248.method_9525(class_2248.java:136)
	at net.minecraft.class_4970$class_4971.method_26164(class_4970.java:938)
	at net.minecraft.class_4970$class_4971$class_3752.handler$zdp000$init(class_4970.java:1115)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1023)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:989)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:642)
	at net.minecraft.class_4970$class_4971.statement_initShapeCache(class_4970.java:2057)
	at virtuoel.statement.util.StateRefresherImpl.lambda$refreshBlockStates$2(StateRefresherImpl.java:100)
	at virtuoel.statement.util.StateRefresherImpl.lambda$null$7(StateRefresherImpl.java:187)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(Unknown Source)
	at virtuoel.statement.util.StateRefresherImpl.lambda$refreshStates$8(StateRefresherImpl.java:185)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 444596224 bytes (424 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx4096m
	Fabric Mods: 
		fabric: Fabric API 0.14.0+build.371-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a977402
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea86602
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.8.9+build.203
		lithium: Lithium 0.5.1
		minecraft: Minecraft 1.16.1
		statement: Statement 3.0.4+1.16.1
		towelette: Towelette 4.1.1+1.16.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# D:\Downloads\mmc-stable-win32(2)\MultiMC\instances\1.16.12\.minecraft\crash-reports\crash-2020-07-30_19.51.24-client.txt
Process exited with code -1.
Clipboard copy at: 30 Jul 2020 19:51:28 -0500

**Comment by Virtuoel** [comment]
Resolved in https://github.com/Virtuoel/Statement/commit/cd39a16ff49750942b7e8f538e344debf0f9e48d
